version: '3.8'
services:
  agent:
    build: ../agent
    ports:
      - "8000:8000"
    volumes:
      - ../resources/resume:/app/resources/resume
  backend:
    build: ../backend
    ports:
      - "8080:8080"
    environment:
      - PYTHON_AGENT_URL=http://agent:8000
    depends_on:
      - agent
